export const Variable = {
	DATABASE_URL: 'DATABASE_URL',
	PORT: 'PORT',
	CLIENT_URL: 'CLIENT_URL',
	SERVER_URL: 'SERVER_URL',

	NODE_ENV: 'NODE_ENV',
	ACCESS_ORIGINS: 'ACCESS_ORIGINS',
	PRODUCTION: 'production',
	DEVELOPMENT: 'development',

	ACCESS_TOKEN_SECRET: 'ACCESS_TOKEN_SECRET',
	ACCESS_TOKEN_EXPIRATION: 'ACCESS_TOKEN_EXPIRATION',
	ACCESS_TOKEN_EXPIRATION_DAYS: 'ACCESS_TOKEN_EXPIRATION_DAYS',
	EMAIL_USER: 'EMAIL_USER'
} as const

export type Variable = (typeof Variable)[keyof typeof Variable]
